# Generated by Django 4.0.6 on 2023-12-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
